Job.create(:job_id => 1, :message_id => 2, :user_id => 1)
Job.create(:job_id => 2, :message_id => 2, :user_id => 2)
Job.create(:job_id => 3, :message_id => 2, :user_id => 3)
Job.create(:job_id => 4, :message_id => 2, :user_id => 4)
Job.create(:job_id => 5, :message_id => 2, :user_id => 5)
